[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dex_retargeting"
version = "0.4.7"
description = "Hand pose retargeting for dexterous robot hand. Modified by [silencht@qq.com]"
authors = [
    { name = "Yuzhe Qin", email = "y1qin@ucsd.edu" }
]
license = { text = "MIT" }
urls = { "Homepage" = "https://github.com/dexsuite/dex-retargeting" }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
